//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShips.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShips.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many incorrect placement commands were made. The ship was removed from your fleet..
        /// </summary>
        internal static string commandsRejectedErrorMessage {
            get {
                return ResourceManager.GetString("commandsRejectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command was not recognised. Ensure that the format is correct eg. 4,5  or  5,2  Enter coordinates to fire your missile....
        /// </summary>
        internal static string fireErrorMessage {
            get {
                return ResourceManager.GetString("fireErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** This game has ended ***
        ///      Press any key to exit....
        /// </summary>
        internal static string gameEndMessage {
            get {
                return ResourceManager.GetString("gameEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game starting.....
        /// </summary>
        internal static string gameStart {
            get {
                return ResourceManager.GetString("gameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enter the coordinates to fire at.....
        /// </summary>
        internal static string getFireCommand {
            get {
                return ResourceManager.GetString("getFireCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode choices.....
        ///
        ///0 - Default game : every player has just one scout and one destroyer ship.
        ///1 - Custom game : choose the the ship types and the quantities needed.
        ///
        ///Enter 0 or 1:.
        /// </summary>
        internal static string getGameMode {
            get {
                return ResourceManager.GetString("getGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mode you entered was not recognised. Try again using a valid number for your game mode..
        /// </summary>
        internal static string getModeErrorMessage {
            get {
                return ResourceManager.GetString("getModeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid name. Name must not be white space or null. Try again..
        /// </summary>
        internal static string getNameErrorMessage {
            get {
                return ResourceManager.GetString("getNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of players for this game (must be two or more):.
        /// </summary>
        internal static string getNumberOfPlayers {
            get {
                return ResourceManager.GetString("getNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command was not recognised. Ensure that the format is correct eg. 4,5,v  or  5,2,h  Enter the coordinates and direction for the ship..
        /// </summary>
        internal static string getPlaceErrorMessage {
            get {
                return ResourceManager.GetString("getPlaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}...
        ///Enter the coordinates and orientation for your ship e.g. 3,4,h or 7,2,v  Hint: All ship positions must lie in the bounds of the sea, and cannot overlap your other ships. Enter the command to place your ship.....
        /// </summary>
        internal static string getPlacementCommand {
            get {
                return ResourceManager.GetString("getPlacementCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name. You must submit any value except spaces or null...:.
        /// </summary>
        internal static string getPlayerName {
            get {
                return ResourceManager.GetString("getPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid number.Two or more players are required for this game..
        /// </summary>
        internal static string getPlayerNoErrorMessage {
            get {
                return ResourceManager.GetString("getPlayerNoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sea dimensions given were not valid. Ensure that the format is correct and that the minimum size is 5,5. Enter the sea dimensions..
        /// </summary>
        internal static string getSeaErrorMessage {
            get {
                return ResourceManager.GetString("getSeaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea setup...
        ///
        ///Note: the sea grid size typed here must be &gt; or = 5 x 5 : Enter the size of the sea, use a comma to separate the x and y dimensions eg. 6,7  Enter the sea size......
        /// </summary>
        internal static string getSeaSize {
            get {
                return ResourceManager.GetString("getSeaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you entered was not recognised. If ships of this kind are not required then type 0.
        /// </summary>
        internal static string getShipNoErrorMessage {
            get {
                return ResourceManager.GetString("getShipNoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of {0}s needed:.
        /// </summary>
        internal static string getShipTypeNo {
            get {
                return ResourceManager.GetString("getShipTypeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Hit!!.
        /// </summary>
        internal static string hitMessage {
            get {
                return ResourceManager.GetString("hitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no ships remaining and has left the game!!.
        /// </summary>
        internal static string leaveMessage {
            get {
                return ResourceManager.GetString("leaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss!!.
        /// </summary>
        internal static string missMessage {
            get {
                return ResourceManager.GetString("missMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...the game mode has been set to {0}..
        /// </summary>
        internal static string modeSetConfirmation {
            get {
                return ResourceManager.GetString("modeSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship not added because at least one position is already occupied or lies outside the sea boundary. Enter the command to place your ship....
        /// </summary>
        internal static string placementErrorMessage {
            get {
                return ResourceManager.GetString("placementErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...your name has been set..
        /// </summary>
        internal static string playerNameSetConfirmation {
            get {
                return ResourceManager.GetString("playerNameSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...this game has {0} players..
        /// </summary>
        internal static string playerNoSetConfirmation {
            get {
                return ResourceManager.GetString("playerNoSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New player setup.....
        /// </summary>
        internal static string playerSetupIntro {
            get {
                return ResourceManager.GetString("playerSetupIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string playerSuffix {
            get {
                return ResourceManager.GetString("playerSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...the sea has been set to {0},{1}.
        /// </summary>
        internal static string seaSetConfirmation {
            get {
                return ResourceManager.GetString("seaSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...{0} ships were chosen..
        /// </summary>
        internal static string shipNoSetConfirmation {
            get {
                return ResourceManager.GetString("shipNoSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...your ship position has been set..
        /// </summary>
        internal static string shipPositionsSetConfirmation {
            get {
                return ResourceManager.GetString("shipPositionsSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship to add: {0}, size {1}.....
        /// </summary>
        internal static string shipTypeDetails {
            get {
                return ResourceManager.GetString("shipTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position hit and {0} sunk!!.
        /// </summary>
        internal static string sinkMessage {
            get {
                return ResourceManager.GetString("sinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** W I N N E R *****
        ///   Congratulations {0}
        ///    You are the winner..
        /// </summary>
        internal static string winMessage {
            get {
                return ResourceManager.GetString("winMessage", resourceCulture);
            }
        }
    }
}
